{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f3a3939-4250-4e40-861b-faad38214fff",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import pickle\n",
    "import numpy as np\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# Set page title\n",
    "st.title(\"Sleep Disorder Prediction App\")\n",
    "\n",
    "# Load the trained logistic regression model\n",
    "try:\n",
    "    with open('logreg_model.pkl', 'rb') as file:\n",
    "        logreg = pickle.load(file)\n",
    "except FileNotFoundError:\n",
    "    st.error(\"Model file 'logreg_model.pkl' not found. Please ensure it is in the same directory.\")\n",
    "    st.stop()\n",
    "\n",
    "# Define the label encoder for decoding predictions\n",
    "label_encoder = LabelEncoder()\n",
    "label_encoder.classes_ = np.array(['Insomnia', 'Sleep Apnea', 'None'])  # Adjust based on notebook's encoding\n",
    "\n",
    "# Sidebar for user inputs\n",
    "st.sidebar.header(\"Enter Patient Details\")\n",
    "\n",
    "# Numerical features\n",
    "age = st.sidebar.slider(\"Age\", min_value=27, max_value=59, value=42)\n",
    "sleep_duration = st.sidebar.slider(\"Sleep Duration (hours)\", min_value=5.8, max_value=8.5, value=7.0, step=0.1)\n",
    "quality_of_sleep = st.sidebar.slider(\"Quality of Sleep (1-10)\", min_value=1, max_value=10, value=7)\n",
    "physical_activity_level = st.sidebar.slider(\"Physical Activity Level (minutes/day)\", min_value=30, max_value=90, value=60)\n",
    "stress_level = st.sidebar.slider(\"Stress Level (1-10)\", min_value=1, max_value=10, value=5)\n",
    "heart_rate = st.sidebar.slider(\"Heart Rate (bpm)\", min_value=65, max_value=86, value=70)\n",
    "daily_steps = st.sidebar.slider(\"Daily Steps\", min_value=3000, max_value=10000, value=7000)\n",
    "systolic_bp = st.sidebar.slider(\"Systolic Blood Pressure\", min_value=110, max_value=150, value=128)\n",
    "diastolic_bp = st.sidebar.slider(\"Diastolic Blood Pressure\", min_value=70, max_value=100, value=85)\n",
    "\n",
    "# Categorical features\n",
    "gender = st.sidebar.selectbox(\"Gender\", options=[\"Male\", \"Female\"])\n",
    "occupation = st.sidebar.selectbox(\"Occupation\", options=[\n",
    "    \"Software Engineer\", \"Doctor\", \"Sales Representative\", \"Nurse\", \"Engineer\",\n",
    "    \"Accountant\", \"Scientist\", \"Lawyer\", \"Salesperson\", \"Teacher\", \"Manager\"\n",
    "])\n",
    "bmi_category = st.sidebar.selectbox(\"BMI Category\", options=[\"Normal\", \"Normal Weight\", \"Overweight\", \"Obese\"])\n",
    "\n",
    "# Function to preprocess input data\n",
    "def preprocess_input(age, sleep_duration, quality_of_sleep, physical_activity_level, stress_level, \n",
    "                    heart_rate, daily_steps, systolic_bp, diastolic_bp, gender, occupation, bmi_category):\n",
    "    # Create a DataFrame with numerical features\n",
    "    data = {\n",
    "        'Age': age,\n",
    "        'Sleep Duration': sleep_duration,\n",
    "        'Quality of Sleep': quality_of_sleep,\n",
    "        'Physical Activity Level': physical_activity_level,\n",
    "        'Stress Level': stress_level,\n",
    "        'Heart Rate': heart_rate,\n",
    "        'Daily Steps': daily_steps,\n",
    "        'Systolic': systolic_bp,\n",
    "        'Diastolic': diastolic_bp\n",
    "    }\n",
    "    df = pd.DataFrame([data])\n",
    "\n",
    "    # One-hot encode categorical features\n",
    "    df['Gender_Female'] = 1 if gender == 'Female' else 0\n",
    "    df['Gender_Male'] = 1 if gender == 'Male' else 0\n",
    "    \n",
    "    # Initialize occupation columns\n",
    "    occupations = ['Accountant', 'Doctor', 'Engineer', 'Lawyer', 'Manager', 'Nurse', \n",
    "                   'Sales Representative', 'Salesperson', 'Scientist', 'Software Engineer', 'Teacher']\n",
    "    for occ in occupations:\n",
    "        df[f'Occupation_{occ}'] = 1 if occupation == occ else 0\n",
    "    \n",
    "    # Initialize BMI category columns\n",
    "    bmi_categories = ['Normal', 'Normal Weight', 'Obese', 'Overweight']\n",
    "    for bmi in bmi_categories:\n",
    "        df[f'BMI Category_{bmi}'] = 1 if bmi_category == bmi else 0\n",
    "\n",
    "    # Ensure all expected columns are present in the correct order\n",
    "    expected_columns = [\n",
    "        'Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level',\n",
    "        'Heart Rate', 'Daily Steps', 'Systolic', 'Diastolic', 'Gender_Female', 'Gender_Male',\n",
    "        'Occupation_Accountant', 'Occupation_Doctor', 'Occupation_Engineer', 'Occupation_Lawyer',\n",
    "        'Occupation_Manager', 'Occupation_Nurse', 'Occupation_Sales Representative',\n",
    "        'Occupation_Salesperson', 'Occupation_Scientist', 'Occupation_Software Engineer',\n",
    "        'Occupation_Teacher', 'BMI Category_Normal', 'BMI Category_Normal Weight',\n",
    "        'BMI Category_Obese', 'BMI Category_Overweight'\n",
    "    ]\n",
    "    df = df.reindex(columns=expected_columns, fill_value=0)\n",
    "    return df\n",
    "\n",
    "# Button to make prediction\n",
    "if st.sidebar.button(\"Predict\"):\n",
    "    # Preprocess the input\n",
    "    input_df = preprocess_input(\n",
    "        age, sleep_duration, quality_of_sleep, physical_activity_level, stress_level,\n",
    "        heart_rate, daily_steps, systolic_bp, diastolic_bp, gender, occupation, bmi_category\n",
    "    )\n",
    "    \n",
    "    # Make prediction\n",
    "    try:\n",
    "        prediction = logreg.predict(input_df)\n",
    "        predicted_label = label_encoder.inverse_transform(prediction)[0]\n",
    "        \n",
    "        # Display result\n",
    "        st.subheader(\"Prediction Result\")\n",
    "        st.write(f\"The predicted sleep disorder is: **{predicted_label}**\")\n",
    "        if predicted_label == \"None\":\n",
    "            st.write(\"No sleep disorder predicted.\")\n",
    "        else:\n",
    "            st.write(f\"The patient may have {predicted_label}.\")\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error making prediction: {str(e)}\")\n",
    "\n",
    "# Display instructions\n",
    "st.write(\"\"\"\n",
    "### Instructions\n",
    "1. Use the sidebar to enter the patient's details.\n",
    "2. Adjust the sliders for numerical features like Age, Sleep Duration, etc.\n",
    "3. Select appropriate options for Gender, Occupation, and BMI Category.\n",
    "4. Click the 'Predict' button to see the predicted sleep disorder.\n",
    "\"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
